### ISSUE TITLE
SMB Plugin Issue

### ISSUE THREAD

**Issue by Tharun-Sabbu** [microsoft/K8s-Storage-Plugins#15]
Hello,

I'm using Kubernetes v1.15.1 with windows server 2019 workers and was using v0.0.3 release of storage plugins on windows workers.

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  smb-deployment
  labels:
    name:  smb-app
  namespace: windows
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smb-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  smb-app
    spec:
      containers:
      - name: smb
        image: microsoft/nanoserver
        command: ["C:\\Windows\\System32\\cmd.exe"]
        args: ["/C", "echo", "0", ">", "c:\\d\\smb_test.txt"]
        volumeMounts:
        - name: smb-volume
          mountPath: c:/data
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
          limits:
            cpu: 200m
            memory: 500Mi
      volumes:
      - name: smb-volume
        flexVolume:
          driver: "microsoft.com/smb.cmd"
          secretRef:
            name: "smb-secret"
          options:
            # source can be in any of the following formats 
            # \\servername\share\path  (\'s will need to be escaped)
            # smb://servername/share/path
            # //servername/share/path
            source: \\10.0.0.5\sharedfolder
      nodeSelector:
        beta.kubernetes.io/os: windows
        kubernetes.io/hostname: ip-0a230df7
```

Here is the error I'm getting in kubelet with debug enabled

"\"flexvolume-microsoft.com/smb.cmd/58b90ea4-e8e0-4549-a71c-6855f1f8b51a-smb-volume\" (\"58b90ea4-e8e0-4549-a71c-6855f1f8b51a\")" failed. No retries permitted until 2019-09-19 04:08:01.8282223 +0000 GMT m=+997.903271801 (durationBeforeRetry 2m2s). Error: "MountVolume.SetUp failed for volume \"smb-volume\" (UniqueName: \"flexvolume-microsoft.com/smb.cmd/58b90ea4-e8e0-4549-a71c-6855f1f8b51a-smb-volume\") pod \"smb-deployment-8585cccf96-g77pv\" (UID: \"58b90ea4-e8e0-4549-a71c-6855f1f8b51a\") : mount command failed, status: Failure, reason: Caught exception The parameter is incorrect.  with stack "

Please let me know if I'm doing something wrong, thanks.
